# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/sys_pll/sys_pll.xci
# IP: The module: 'sys_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/sys_pll/sys_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/sys_pll/sys_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/sys_pll/sys_pll_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/sys_pll/sys_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/sys_pll/sys_pll.xci
# IP: The module: 'sys_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/sys_pll/sys_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/sys_pll/sys_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/sys_pll/sys_pll_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/sys_pll/sys_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
