############## NET - IOSTANDARD #######################
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
#############SPI Configurate Setting###################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design] 
set_property CONFIG_MODE SPIx4 [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design] 
############## clock define############################
create_clock -period 20 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {sys_clk}]
set_property PACKAGE_PIN Y18 [get_ports {sys_clk}]
##############J9 on ax7035 #############################
set_property PACKAGE_PIN D16 [get_ports {da1_data[13]}]
set_property PACKAGE_PIN E16 [get_ports {da1_data[12]}]
set_property PACKAGE_PIN F14 [get_ports {da1_data[11]}]
set_property PACKAGE_PIN F13 [get_ports {da1_data[10]}]
set_property PACKAGE_PIN E14 [get_ports {da1_data[9]}]
set_property PACKAGE_PIN E13 [get_ports {da1_data[8]}]
set_property PACKAGE_PIN D15 [get_ports {da1_data[7]}]
set_property PACKAGE_PIN D14 [get_ports {da1_data[6]}]
set_property PACKAGE_PIN B13 [get_ports {da1_data[5]}]
set_property PACKAGE_PIN C13 [get_ports {da1_data[4]}]
set_property PACKAGE_PIN A14 [get_ports {da1_data[3]}]
set_property PACKAGE_PIN A13 [get_ports {da1_data[2]}]
set_property PACKAGE_PIN C15 [get_ports {da1_data[1]}]
set_property PACKAGE_PIN C14 [get_ports {da1_data[0]}]
set_property PACKAGE_PIN A16 [get_ports {da1_wrt}]
set_property PACKAGE_PIN A15 [get_ports {da1_clk}]

set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_wrt}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_clk}]

set_property PACKAGE_PIN B16 [get_ports {da2_clk}]
set_property PACKAGE_PIN B15 [get_ports {da2_wrt}]
set_property PACKAGE_PIN B18 [get_ports {da2_data[13]}]
set_property PACKAGE_PIN B17 [get_ports {da2_data[12]}]
set_property PACKAGE_PIN A19 [get_ports {da2_data[11]}]
set_property PACKAGE_PIN A18 [get_ports {da2_data[10]}]
set_property PACKAGE_PIN C19 [get_ports {da2_data[9]}]
set_property PACKAGE_PIN C18 [get_ports {da2_data[8]}]
set_property PACKAGE_PIN A20 [get_ports {da2_data[7]}]
set_property PACKAGE_PIN B20 [get_ports {da2_data[6]}]
set_property PACKAGE_PIN C17 [get_ports {da2_data[5]}]
set_property PACKAGE_PIN D17 [get_ports {da2_data[4]}]
set_property PACKAGE_PIN D19 [get_ports {da2_data[3]}]
set_property PACKAGE_PIN E19 [get_ports {da2_data[2]}]
set_property PACKAGE_PIN E18 [get_ports {da2_data[1]}]
set_property PACKAGE_PIN F18 [get_ports {da2_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {da2_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_wrt}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[0]}]



