# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: I:/ax7035_2019.1/demo/15_3_lcd_an070_char/lcd_an070_char/lcd_char_an070.srcs/sources_1/ip/osd_rom/osd_rom.xci
# IP: The module: 'osd_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ax7035_2019.1/demo/15_3_lcd_an070_char/lcd_an070_char/lcd_char_an070.srcs/sources_1/ip/osd_rom/osd_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'osd_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: I:/ax7035_2019.1/demo/15_3_lcd_an070_char/lcd_an070_char/lcd_char_an070.srcs/sources_1/ip/osd_rom/osd_rom.xci
# IP: The module: 'osd_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ax7035_2019.1/demo/15_3_lcd_an070_char/lcd_an070_char/lcd_char_an070.srcs/sources_1/ip/osd_rom/osd_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'osd_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
