# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.cache/wt [current_project]
set_property parent.project_path I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/src/ad7606_if.v
  I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/src/ad7606_sample.v
  I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/src/video_define.v
  I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/src/color_bar.v
  I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/src/grid_display.v
  I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/src/timing_gen_xy.v
  I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/src/wav_display.v
  I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/src/top.v
}
read_vhdl -library xil_defaultlib {
  I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/src/SyncAsync.vhd
  I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/src/SyncAsyncReset.vhd
  I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/src/ClockGen.vhd
  I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/src/DVI_Constants.vhd
  I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/src/OutputSERDES.vhd
  I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/src/TMDS_Encoder.vhd
  I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/src/rgb2dvi.vhd
}
read_ip -quiet I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/adc_pll/adc_pll.xci
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/adc_pll/adc_pll_board.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/adc_pll/adc_pll.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/adc_pll/adc_pll_late.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/adc_pll/adc_pll_ooc.xdc]

read_ip -quiet I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/dpram1024x8/dpram1024x8.xci
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/dpram1024x8/dpram1024x8_ooc.xdc]

read_ip -quiet I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/video_pll/video_pll.xci
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/video_pll/video_pll_board.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/video_pll/video_pll.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/video_pll/video_pll_late.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/video_pll/video_pll_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/constrs_1/new/ad7606_hdmi_test.xdc
set_property used_in_implementation false [get_files I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/constrs_1/new/ad7606_hdmi_test.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
