# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: I:/ax7035_2019.1/demo/26_ethernet_test/ethernet_test/rgmii_ethernet/eth_test.srcs/sources_1/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256.xci
# IP: The module: 'icmp_rx_ram_8_256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ax7035_2019.1/demo/26_ethernet_test/ethernet_test/rgmii_ethernet/eth_test.srcs/sources_1/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'icmp_rx_ram_8_256'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: I:/ax7035_2019.1/demo/26_ethernet_test/ethernet_test/rgmii_ethernet/eth_test.srcs/sources_1/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256.xci
# IP: The module: 'icmp_rx_ram_8_256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ax7035_2019.1/demo/26_ethernet_test/ethernet_test/rgmii_ethernet/eth_test.srcs/sources_1/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'icmp_rx_ram_8_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
