# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128.xci
# IP: The module: 'afifo_64i_32o_128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64i_32o_128'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64i_32o_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64i_32o_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128.xci
# IP: The module: 'afifo_64i_32o_128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64i_32o_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64i_32o_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64i_32o_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
