# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.cache/wt [current_project]
set_property parent.project_path I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/aq_axi_master.v
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/audio_key.v
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/audio_record_play_ctrl.v
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/audio_rx.v
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/audio_tx.v
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/ax_debounce.v
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/frame_fifo_read.v
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/frame_fifo_write.v
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/frame_read_write.v
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/i2c_master/i2c_config.v
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/i2c_master/timescale.v
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/i2c_master/i2c_master_defines.v
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/i2c_master/i2c_master_bit_ctrl.v
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/i2c_master/i2c_master_byte_ctrl.v
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/i2c_master/i2c_master_top.v
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/lut_wm8731.v
  I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/src/top.v
}
read_ip -quiet I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/clk_200M/clk_200M.xci
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/clk_200M/clk_200M_board.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/clk_200M/clk_200M.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/clk_200M/clk_200M_ooc.xdc]

read_ip -quiet I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/ddr3/ddr3.xci
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/ddr3/ddr3/user_design/constraints/ddr3.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/ddr3/ddr3/user_design/constraints/ddr3_ooc.xdc]

read_ip -quiet I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/afifo_64_256/afifo_64_256.xci
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/afifo_64_256/afifo_64_256.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/afifo_64_256/afifo_64_256_clocks.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/afifo_64_256/afifo_64_256_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/constrs_1/new/audio_record_play.xdc
set_property used_in_implementation false [get_files I:/ax7035_2019.1/demo/13_audio_record_play/audio_record_play/audio_record_play.srcs/constrs_1/new/audio_record_play.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
