# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: I:/ax7035_2019.1/demo/23_ad9767_dual_trig_wave/ad9767_dual_trig_wave/an9767_test.srcs/sources_1/ip/PLL/PLL.xci
# IP: The module: 'PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ax7035_2019.1/demo/23_ad9767_dual_trig_wave/ad9767_dual_trig_wave/an9767_test.srcs/sources_1/ip/PLL/PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/23_ad9767_dual_trig_wave/ad9767_dual_trig_wave/an9767_test.srcs/sources_1/ip/PLL/PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/23_ad9767_dual_trig_wave/ad9767_dual_trig_wave/an9767_test.srcs/sources_1/ip/PLL/PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: I:/ax7035_2019.1/demo/23_ad9767_dual_trig_wave/ad9767_dual_trig_wave/an9767_test.srcs/sources_1/ip/PLL/PLL.xci
# IP: The module: 'PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ax7035_2019.1/demo/23_ad9767_dual_trig_wave/ad9767_dual_trig_wave/an9767_test.srcs/sources_1/ip/PLL/PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/23_ad9767_dual_trig_wave/ad9767_dual_trig_wave/an9767_test.srcs/sources_1/ip/PLL/PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/23_ad9767_dual_trig_wave/ad9767_dual_trig_wave/an9767_test.srcs/sources_1/ip/PLL/PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
