# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.cache/wt [current_project]
set_property parent.project_path I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/src/aq_axi_master.v
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/src/ax_debounce.v
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/src/bmp_read.v
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/src/video_define.v
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/src/color_bar.v
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/src/frame_fifo_read.v
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/src/frame_fifo_write.v
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/src/frame_read_write.v
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/src/sd_card_bmp.v
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/src/sd_card/sd_card_cmd.v
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/src/sd_card/sd_card_sec_read_write.v
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/src/sd_card/sd_card_top.v
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/src/sd_card/spi_master.v
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/src/video_timing_data.v
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/src/top.v
}
read_vhdl -library xil_defaultlib {
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/src/SyncAsync.vhd
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/src/SyncAsyncReset.vhd
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/src/ClockGen.vhd
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/src/DVI_Constants.vhd
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/src/OutputSERDES.vhd
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/src/TMDS_Encoder.vhd
  I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/src/rgb2dvi.vhd
}
read_ip -quiet I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/ddr3/ddr3.xci
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/ddr3/ddr3/user_design/constraints/ddr3.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/ddr3/ddr3/user_design/constraints/ddr3_ooc.xdc]

read_ip -quiet I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256.xci
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256_clocks.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256_ooc.xdc]

read_ip -quiet I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/clk_200M/clk_200M.xci
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/clk_200M/clk_200M_board.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/clk_200M/clk_200M.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/clk_200M/clk_200M_ooc.xdc]

read_ip -quiet I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128.xci
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128_clocks.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128_ooc.xdc]

read_ip -quiet I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/video_pll/video_pll.xci
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/video_pll/video_pll_board.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/video_pll/video_pll.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/video_pll/video_pll_late.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/video_pll/video_pll_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/constrs_1/new/sd_picture_hdmi.xdc
set_property used_in_implementation false [get_files I:/ax7035_2019.1/demo/16_1_sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/constrs_1/new/sd_picture_hdmi.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
