# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.cache/wt [current_project]
set_property parent.project_path I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/imports/sources_1/aq_axi_master.v
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/imports/sources_1/video_define.v
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/imports/sources_1/color_bar.v
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/imports/sources_1/frame_fifo_read.v
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/imports/sources_1/frame_fifo_write.v
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/imports/sources_1/frame_read_write.v
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/imports/sources_1/video_timing_data.v
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/imports/sources_1/video_write_req_gen.v
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/imports/sources_1/top.v
}
read_vhdl -library xil_defaultlib {
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/DVI_Constants.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/ChannelBond.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/SyncAsync.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/SyncAsyncReset.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/ClockGen.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/GlitchFilter.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/TWI_SlaveCtl.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/EEPROM_8b.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/InputSERDES.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/OutputSERDES.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/PhaseAlign.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/ResyncToBUFG.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/SyncBase.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/TMDS_Clocking.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/TMDS_Decoder.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/TMDS_Encoder.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/dvi2rgb.vhd
  I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/src/rgb2dvi.vhd
}
read_ip -quiet I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/sys_pll/sys_pll.xci
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/sys_pll/sys_pll_board.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/sys_pll/sys_pll.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/sys_pll/sys_pll_late.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/sys_pll/sys_pll_ooc.xdc]

read_ip -quiet I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/afifo_32i_64o_4096/afifo_32i_64o_4096.xci
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/afifo_32i_64o_4096/afifo_32i_64o_4096.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/afifo_32i_64o_4096/afifo_32i_64o_4096_clocks.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/afifo_32i_64o_4096/afifo_32i_64o_4096_ooc.xdc]

read_ip -quiet I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/axi_interconnect/axi_interconnect.xci
set_property used_in_synthesis false [get_files -all i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/axi_interconnect/axi_interconnect_impl_clocks.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/axi_interconnect/axi_interconnect_impl_clocks.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/axi_interconnect/axi_interconnect_ooc.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/axi_interconnect/axi_interconnect_clocks.xdc]

read_ip -quiet I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/afifo_64i_32o_2048/afifo_64i_32o_2048.xci
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/afifo_64i_32o_2048/afifo_64i_32o_2048.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/afifo_64i_32o_2048/afifo_64i_32o_2048_clocks.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/afifo_64i_32o_2048/afifo_64i_32o_2048_ooc.xdc]

read_ip -quiet i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/ddr3/ddr3.xci
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/ddr3/ddr3/user_design/constraints/ddr3.xdc]
set_property used_in_implementation false [get_files -all i:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/sources_1/ip/ddr3/ddr3/user_design/constraints/ddr3_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/constrs_1/imports/sources_1/top.xdc
set_property used_in_implementation false [get_files I:/ax7035_2019.1/14_4hdmi_input_loopback_ddrOK/hdmi_input_loopback_ddr/hdmi_input_loopback_ddr.srcs/constrs_1/imports/sources_1/top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
