# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/adc_pll/adc_pll.xci
# IP: The module: 'adc_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/adc_pll/adc_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/adc_pll/adc_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/adc_pll/adc_pll_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/adc_pll/adc_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: I:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/adc_pll/adc_pll.xci
# IP: The module: 'adc_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/adc_pll/adc_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/adc_pll/adc_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/adc_pll/adc_pll_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/20_ad7606_hdmi_test/ad7606_hdmi_test/ad7606_hdmi_test.srcs/sources_1/ip/adc_pll/adc_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
