# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: I:/ax7035_2019.1/demo/21_an108_adda_hdmi_test/an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/adda_pll/adda_pll.xci
# IP: The module: 'adda_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ax7035_2019.1/demo/21_an108_adda_hdmi_test/an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/adda_pll/adda_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'adda_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/21_an108_adda_hdmi_test/an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/adda_pll/adda_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'adda_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/21_an108_adda_hdmi_test/an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/adda_pll/adda_pll_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'adda_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/21_an108_adda_hdmi_test/an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/adda_pll/adda_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adda_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: I:/ax7035_2019.1/demo/21_an108_adda_hdmi_test/an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/adda_pll/adda_pll.xci
# IP: The module: 'adda_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ax7035_2019.1/demo/21_an108_adda_hdmi_test/an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/adda_pll/adda_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'adda_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/21_an108_adda_hdmi_test/an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/adda_pll/adda_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'adda_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/21_an108_adda_hdmi_test/an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/adda_pll/adda_pll_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'adda_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: i:/ax7035_2019.1/demo/21_an108_adda_hdmi_test/an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/adda_pll/adda_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adda_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
